#!/usr/bin/env bash
# ─── ChitChat on Hostinger KVM — one-shot VPS setup ───────────────────────────
# Run as root on the VPS:  sudo bash hostinger-vps-setup.sh
#
# What it does:
#   1. Removes n8n (docker container/image, systemd service, npm global, pm2 app,
#      leftover dirs, frees port 5678)
#   2. Installs requirements: Node.js 20, git, nginx, certbot, pm2
#   3. Clones/updates the ChitChat repo to /opt/chitchat, installs deps, builds
#   4. Writes production env files, starts server (:4000) + web (:3000) via pm2
#   5. Configures nginx reverse proxy (single domain, /socket.io → :4000) + SSL
#
# ── EDIT THESE BEFORE RUNNING ─────────────────────────────────────────────────
DOMAIN="example.com"                    # your domain, DNS A-record → this VPS IP
EMAIL="you@example.com"                 # for Let's Encrypt expiry notices
REPO_URL="https://github.com/Riaz123islam/chitchat.git"
APP_DIR="/opt/chitchat"
# Optional integrations (leave empty to skip — app degrades gracefully):
UPSTASH_REDIS_REST_URL=""
UPSTASH_REDIS_REST_TOKEN=""
SUPABASE_URL=""
SUPABASE_SERVICE_ROLE_KEY=""
TURNSTILE_SECRET_KEY=""
NEXT_PUBLIC_TURNSTILE_SITE_KEY=""
ADMIN_TOKEN=""                          # set a strong random value to enable /admin
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail
if [ "$(id -u)" -ne 0 ]; then echo "Run as root: sudo bash $0"; exit 1; fi
export DEBIAN_FRONTEND=noninteractive

echo "=== [1/7] Removing n8n ==="
# — Docker installs —
if command -v docker >/dev/null 2>&1; then
  N8N_CONTAINERS=$(docker ps -aq --filter "name=n8n" 2>/dev/null || true)
  # also catch containers publishing n8n's default port 5678
  PORT_CONTAINERS=$(docker ps -aq --filter "publish=5678" 2>/dev/null || true)
  for c in $N8N_CONTAINERS $PORT_CONTAINERS; do
    echo "Removing docker container $c"; docker rm -f "$c" || true
  done
  N8N_IMAGES=$(docker images -q "n8nio/n8n" 2>/dev/null || true)
  for i in $N8N_IMAGES; do echo "Removing docker image $i"; docker rmi -f "$i" || true; done
fi
if [ -f /opt/n8n/docker-compose.yml ] || [ -f /root/n8n/docker-compose.yml ]; then
  echo "Found n8n docker-compose dir — remove it manually after checking: /opt/n8n /root/n8n"
fi
# — systemd service —
if systemctl list-unit-files | grep -q "^n8n"; then
  systemctl stop n8n || true; systemctl disable n8n || true
  rm -f /etc/systemd/system/n8n.service; systemctl daemon-reload
  echo "Removed n8n systemd service"
fi
# — npm global —
if npm ls -g --depth=0 2>/dev/null | grep -q "n8n"; then npm rm -g n8n || true; echo "Removed global npm n8n"; fi
# — pm2 app named n8n —
if command -v pm2 >/dev/null 2>&1; then pm2 delete n8n 2>/dev/null || true; fi
# — processes on port 5678 (n8n default) —
if command -v fuser >/dev/null 2>&1; then fuser -k 5678/tcp 2>/dev/null || true; fi
# — leftover data dirs (config/workflows live here — delete only if you don't need them) —
for d in /root/.n8n /home/*/.n8n /opt/n8n /root/n8n; do
  [ -e "$d" ] && echo "NOTE: leftover n8n dir $d — delete manually with: rm -rf $d"
done
echo "n8n removal done."

echo "=== [2/7] Installing system requirements ==="
apt-get update -y
apt-get install -y curl git nginx certbot python3-certbot-nginx ufw psmisc
# Node.js 20 (NodeSource)
if ! command -v node >/dev/null 2>&1 || [ "$(node -v | cut -d. -f1 | tr -d 'v')" -lt 20 ]; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
fi
node -v; npm -v
npm install -g pm2@latest

echo "=== [3/7] Firewall ==="
ufw allow 22/tcp >/dev/null 2>&1 || true
ufw allow 80/tcp >/dev/null 2>&1 || true
ufw allow 443/tcp >/dev/null 2>&1 || true
ufw --force enable >/dev/null 2>&1 || true

echo "=== [4/7] Fetching ChitChat source ==="
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" pull --ff-only || echo "WARN: git pull failed, keeping existing code"
else
  rm -rf "$APP_DIR"; git clone "$REPO_URL" "$APP_DIR"
fi
cd "$APP_DIR"
npm ci || npm install

echo "=== [5/7] Writing production env files ==="
# Web: Next.js bakes NEXT_PUBLIC_* vars in at build time from .env.production.
WEB_ENV="$APP_DIR/apps/web/.env.production"
cat > "$WEB_ENV" <<EOF
# generated by hostinger-vps-setup.sh on $(date -u +%FT%TZ)
NEXT_PUBLIC_APP_URL=https://$DOMAIN
NEXT_PUBLIC_SOCKET_URL=https://$DOMAIN
NEXT_PUBLIC_TURNSTILE_SITE_KEY=$NEXT_PUBLIC_TURNSTILE_SITE_KEY
EOF
echo "Web env written. (Server env goes into the pm2 ecosystem file in step 6 —
the server reads process.env directly, no dotenv.)"

echo "=== [6/7] Building + starting with pm2 ==="
npm run build
# NOTE: the server reads process.env directly (no dotenv), so env vars are
# injected via a pm2 ecosystem file. Next.js already baked NEXT_PUBLIC_*
# vars in at build time from apps/web/.env.production.
ECOSYSTEM="$APP_DIR/ecosystem.config.cjs"
cat > "$ECOSYSTEM" <<EOF
// generated by hostinger-vps-setup.sh on $(date -u +%FT%TZ)
module.exports = {
  apps: [
    {
      name: "chitchat-server",
      cwd: "$APP_DIR/apps/server",
      script: "dist/index.js",
      env: {
        NODE_ENV: "production",
        PORT: "4000",
        SOCKET_SERVER_URL: "https://$DOMAIN",
        ALLOWED_ORIGINS: "https://$DOMAIN",
        UPSTASH_REDIS_REST_URL: "$UPSTASH_REDIS_REST_URL",
        UPSTASH_REDIS_REST_TOKEN: "$UPSTASH_REDIS_REST_TOKEN",
        SUPABASE_URL: "$SUPABASE_URL",
        SUPABASE_SERVICE_ROLE_KEY: "$SUPABASE_SERVICE_ROLE_KEY",
        TURNSTILE_SECRET_KEY: "$TURNSTILE_SECRET_KEY",
        ADMIN_TOKEN: "$ADMIN_TOKEN",
      },
    },
    {
      name: "chitchat-web",
      cwd: "$APP_DIR/apps/web",
      script: "npm",
      args: "start -- -p 3000",
      env: { NODE_ENV: "production", PORT: "3000" },
    },
  ],
};
EOF
chmod 600 "$ECOSYSTEM"
pm2 delete chitchat-server 2>/dev/null || true
pm2 delete chitchat-web 2>/dev/null || true
pm2 start "$ECOSYSTEM" --update-env
pm2 save
pm2 startup systemd -u root --hp /root >/dev/null 2>&1 || true
pm2 save
sleep 3
pm2 list
curl -sf http://localhost:4000/health && echo "server /health OK" || echo "WARN: server /health not responding yet"
curl -sf -o /dev/null http://localhost:3000 && echo "web :3000 OK" || echo "WARN: web :3000 not responding yet"

echo "=== [7/7] Nginx reverse proxy + SSL ==="
NGINX_CONF="/etc/nginx/sites-available/chitchat"
cat > "$NGINX_CONF" <<EOF
# ChitChat — generated by hostinger-vps-setup.sh
server {
    listen 80;
    server_name $DOMAIN;
    client_max_body_size 2m;

    # Socket.IO (websocket + polling) → Node server :4000
    location /socket.io/ {
        proxy_pass http://127.0.0.1:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # Health + admin API → server :4000 (keeps /admin unlisted, not linked).
    # NOTE: /admin (exact) is the Next.js admin page → must NOT match here;
    # only /admin/<api> and /health go to the backend.
    location ~ ^/(health|admin/) {
        proxy_pass http://127.0.0.1:4000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Everything else → Next.js :3000
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
    }
}
EOF
ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/chitchat
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx
# SSL (needs DNS A record for $DOMAIN → this server already propagated)
certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos -m "$EMAIL" --redirect || \
  echo "WARN: certbot failed — is DNS pointing at this server? Re-run: certbot --nginx -d $DOMAIN"
systemctl enable nginx certbot.timer 2>/dev/null || true

echo ""
echo "──────── Done ────────"
echo "Frontend: https://$DOMAIN"
echo "Health:   https://$DOMAIN/health"
echo "pm2 apps: pm2 list | pm2 logs chitchat-server | pm2 logs chitchat-web"
echo "Redeploy after git push: cd $APP_DIR && git pull && npm ci && npm run build && pm2 restart all"
echo "(If you change the values at the top of this script, re-run it to regenerate the ecosystem file.)"
